POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer xxx

{
  "title": "v2.35.0-cloud.1 : Changelog",
  "author": "Hasura Team",
  "likes": 0
}

#replace token with valid token